services:
    database_configuration:
        class: \Doctrine\DBAL\Configuration

    database_connection:
        class: \Doctrine\DBAL\Driver\Connection
        factory: [\Doctrine\DBAL\DriverManager, getConnection]
        arguments: [{url: 'mysql://root:koala321@localhost/bof_test'}, '@database_configuration']