services:
    app.command.test_reset_data:
        class: BOF\Command\TestDataResetCommand
        tags:
            - { name: console.command }

    app.command.report_yearly:
        class: BOF\Command\ReportYearlyCommand
        tags:
            - { name: console.command }

    app.command.generate_reports:
        class: BOF\Command\GenerateReportsCommand
        tags:
            - { name: console.command }

    app.command.update_reports:
        class: BOF\Command\UpdateReportsCommand
        tags:
            - { name: console.command }